### ISSUE TITLE
Regarding booting Up Cm-14.1

### ISSUE THREAD

**Issue by mohancm** [vampirefo/android_vendor_blu_p6601#1]
hey, i wanted to ask  you about booting cm-14.1 on 3.18.19 kernel
1)Are these libdpframework libs are necessary to boot cm-14.1?
2)Are you tried booting without these?

**Comment by vampirefo** [comment]
I haven't tried to boot without them,  I just added everything I thought I would need to get a working rom.

I use Lineage OS sources now instead of CM, no matter though both sources work just fine.

**Comment by mohancm** [comment]
i am not able to boot lineage-14.1 with my stock blobs,if i use M.A.D team vendors,it will boot but i will get lots of bugs.
To get rid of bugs ,i need to use my vendors, But not booting with my blobs.Can you help with this.
Thank you

**Comment by vampirefo** [comment]
No, I can't help, M.A.D Team knows much more about MTK than I do, they maybe able to help you.
Blobs are trial and error, you just have to keep adding and removing blobs until you get the right combo.
I use this tool to find blobs. 

https://github.com/vampirefo/Android-Blob-Utility

I am going to close this issue as it's not really an issue, my vendor blobs work as they should on my device.

**Comment by mohancm** [comment]
ok thanks for your info.
